# Generated by Django 4.2.3 on 2023-07-28 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(blank=True, related_name='author_rn', to='catalog.author', verbose_name='Автор'),
        ),
    ]
